name: "Sphinx Docs Check"
on:
  push:
    paths:
    - 'source/**'
    - 'requirements.txt'
    - '.github/workflows/sphinx*yml'
  pull_request:
    paths:
    - 'source/**'
    - 'requirements.txt'
    - '.github/workflows/sphinx*yml'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout redata-commons
      uses: actions/checkout@v2
    - name: Sphinx build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./"
